name: Build and Deploy to Google Compute Engine

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ✅ Step 1: Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v3

      # ✅ Step 2: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # ✅ Step 3: Configure Docker
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      # ✅ Step 4: Build Docker image with build-time secrets
      - name: Build Docker image
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY="${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}" \
            --build-arg STRIPE_SECRET_KEY="${{ secrets.STRIPE_SECRET_KEY }}" \
            --build-arg NEXT_PUBLIC_URL="${{ secrets.NEXT_PUBLIC_URL }}" \
            --build-arg NEXTAUTH_URL="${{ secrets.NEXTAUTH_URL }}" \
            --build-arg NEXTAUTH_SECRET="${{ secrets.NEXTAUTH_SECRET }}" \
            --build-arg MONGODB_URI="${{ secrets.MONGODB_URI }}" \
            --build-arg GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
            --build-arg GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
            --build-arg GITHUB_CLIENT_ID="${{ secrets.GITHUB_CLIENT_ID }}" \
            --build-arg GITHUB_CLIENT_SECRET="${{ secrets.GITHUB_CLIENT_SECRET }}" \
            --build-arg EBAY_CLIENT_ID="${{ secrets.EBAY_CLIENT_ID }}" \
            --build-arg EBAY_CLIENT_SECRET="${{ secrets.EBAY_CLIENT_SECRET }}" \
            -t gcr.io/melodic-bazaar-455504-q5/jewelry-ecommerce:latest .

      # ✅ Step 5: Push image to Google Container Registry
      - name: Push Docker image to GCR
        run: docker push gcr.io/melodic-bazaar-455504-q5/jewelry-ecommerce:latest

      # ✅ Step 6: SSH into VM and deploy
      - name: SSH and deploy to Compute Engine VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_SSH_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            docker pull gcr.io/melodic-bazaar-455504-q5/jewelry-ecommerce:latest
            docker stop jewelry-ecommerce || true
            docker rm jewelry-ecommerce || true
            docker run -d --name jewelry-ecommerce -p 8080:8080 \
              -e NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY="${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}" \
              -e STRIPE_SECRET_KEY="${{ secrets.STRIPE_SECRET_KEY }}" \
              -e NEXT_PUBLIC_URL="${{ secrets.NEXT_PUBLIC_URL }}" \
              -e NEXTAUTH_URL="${{ secrets.NEXTAUTH_URL }}" \
              -e NEXTAUTH_SECRET="${{ secrets.NEXTAUTH_SECRET }}" \
              -e MONGODB_URI="${{ secrets.MONGODB_URI }}" \
              -e GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
              -e GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
              -e GITHUB_CLIENT_ID="${{ secrets.GITHUB_CLIENT_ID }}" \
              -e GITHUB_CLIENT_SECRET="${{ secrets.GITHUB_CLIENT_SECRET }}" \
              -e EBAY_CLIENT_ID="${{ secrets.EBAY_CLIENT_ID }}" \
              -e EBAY_CLIENT_SECRET="${{ secrets.EBAY_CLIENT_SECRET }}" \
              gcr.io/melodic-bazaar-455504-q5/jewelry-ecommerce:latest
