name: Deploy to GCE VM

on:
  push:
    branches:
      - main  # Trigger deployment only on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GCE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.GCE_VM_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy Docker container to VM
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.GCE_VM_USER }}@${{ secrets.GCE_VM_HOST }} << 'EOF'
          docker pull gcr.io/melodic-bazaar-455504-q5/jewelry-ecommerce:latest
          docker stop $(docker ps -q --filter ancestor=gcr.io/melodic-bazaar-455504-q5/jewelry-ecommerce) || true
          docker rm $(docker ps -a -q --filter ancestor=gcr.io/melodic-bazaar-455504-q5/jewelry-ecommerce) || true
          docker run -d -p 80:3000 gcr.io/melodic-bazaar-455504-q5/jewelry-ecommerce:latest
        EOF
